config:
  probes:
    address: :7070
  log:
    level: info
  drain:
    seconds: 20
  listen:
    address: :8080
images:
  urls:
    registry: ghcr.io
    repository: truvity/policy/url-shortener/urls
    tag: ''
    digest: ''