// Generates src/schemas.generated.ts from the schemas this repository
// publishes, so the package carries them and validation needs no network —
// the same property the Go module gets from embedding.
//
// Generated code is committed and the `drift` recipe fails on a diff: a
// fragment edited without regenerating would leave the two loaders validating
// different documents, which is the one thing this repository exists to
// prevent.
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("../..", import.meta.url).pathname;
const schemasDir = join(root, "schemas");

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return walk(full);
    return full.endsWith(".json") ? [full] : [];
  });
}

const base = "https://github.com/truvity/policy/schemas/";
const entries = walk(schemasDir)
  .sort()
  .map((file) => {
    const id = base + relative(schemasDir, file).split(/[\\/]/).join("/");
    const doc = JSON.parse(readFileSync(file, "utf8"));
    if (doc.$id !== id) {
      throw new Error(
        `${file}: $id is ${doc.$id}, expected ${id}. A document registered under a name nothing refers to is a reference that silently resolves to nothing.`,
      );
    }
    return [id, doc];
  });

const out = `// Code generated by \`just ts-schemas\`. DO NOT EDIT.
//
// The shapes this repository publishes, by the identifier each carries. They
// are values here rather than files so that the published package is
// self-contained and validation never reaches the network.

export const SCHEMA_BASE = ${JSON.stringify(base)};

export const sharedSchemas: Record<string, object> = ${JSON.stringify(
  Object.fromEntries(entries),
  null,
  2,
)};
`;

writeFileSync(join(root, "ts/src/schemas.generated.ts"), out);
console.log(`wrote ts/src/schemas.generated.ts: ${entries.length} schemas`);
