// Generates, for every loader this repository ships, the schemas it carries,
// so that validation needs no network — the same property the Go module gets
// from embedding.
//
// ONE generator for all of them, deliberately. Two would be two things to
// remember, and the failure mode of forgetting the second is two loaders
// validating different documents, which is the one thing this repository
// exists to prevent.
//
// Generated code is committed and the `drift` recipe fails on a diff: a
// fragment edited without regenerating would leave the two loaders validating
// different documents, which is the one thing this repository exists to
// prevent.
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const schemasDir = join(root, "schemas");

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return walk(full);
    return full.endsWith(".json") ? [full] : [];
  });
}

const base = "https://github.com/truvity/policy/schemas/";
const entries = walk(schemasDir)
  .sort()
  .map((file) => {
    const id = base + relative(schemasDir, file).split(/[\\/]/).join("/");
    const doc = JSON.parse(readFileSync(file, "utf8"));
    if (doc.$id !== id) {
      throw new Error(
        `${file}: $id is ${doc.$id}, expected ${id}. A document registered under a name nothing refers to is a reference that silently resolves to nothing.`,
      );
    }
    return [id, doc];
  });

const out = `// Code generated by \`just ts-schemas\`. DO NOT EDIT.
//
// The shapes this repository publishes, by the identifier each carries. They
// are values here rather than files so that the published package is
// self-contained and validation never reaches the network.

export const SCHEMA_BASE = ${JSON.stringify(base)};

export const sharedSchemas: Record<string, object> = ${JSON.stringify(
  Object.fromEntries(entries),
  null,
  2,
)};
`;

writeFileSync(join(root, "ts/src/schemas.generated.ts"), out);

const python = `"""The shapes this repository publishes, by the identifier each carries.

Generated by \`just schemas\`. DO NOT EDIT.

They are values here rather than files so that the installed package is
self-contained and validation never reaches the network.
"""

from typing import Any

SCHEMA_BASE = ${JSON.stringify(base)}

SHARED_SCHEMAS: dict[str, dict[str, Any]] = ${JSON.stringify(
  Object.fromEntries(entries),
  null,
  4,
)
  .replace(/\btrue\b/g, "True")
  .replace(/\bfalse\b/g, "False")
  .replace(/\bnull\b/g, "None")}
`;

writeFileSync(join(root, "python/src/truvity_policy/schemas.py"), python);

console.log(`wrote the schemas both loaders carry: ${entries.length} of them`);
