"""The shapes this repository publishes, by the identifier each carries.

Generated by `just schemas`. DO NOT EDIT.

They are values here rather than files so that the installed package is
self-contained and validation never reaches the network.
"""

from typing import Any

SCHEMA_BASE = "https://github.com/truvity/policy/schemas/"

SHARED_SCHEMAS: dict[str, dict[str, Any]] = {
    "https://github.com/truvity/policy/schemas/fragments/bucket.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/bucket.json",
        "title": "bucket",
        "description": "An object store addressed by the S3 API. The vendor is not part of the configuration: an endpoint, a region and a path-style flag are enough to reach a cloud service, an in-cluster store or a test double, and a service that hard-codes one of them cannot be tested without it.",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "name"
        ],
        "properties": {
            "name": {
                "type": "string",
                "minLength": 1,
                "description": "The bucket. It exists already: a service does not create its own store."
            },
            "region": {
                "type": "string",
                "minLength": 1,
                "description": "The region the bucket is in."
            },
            "endpoint": {
                "type": "string",
                "format": "uri",
                "description": "Override the API endpoint. Unset means the SDK's own resolution for the region."
            },
            "ca": {
                "type": "string",
                "minLength": 1,
                "description": "Path to a certificate authority bundle the platform mounts, for a store whose endpoint is not signed by a public root. A store inside somebody's own network is the ordinary case, not the exotic one. Unset means the system trust store."
            },
            "pathStyle": {
                "type": "boolean",
                "default": False,
                "description": "Address the bucket as a path rather than as a host. Required by most non-cloud implementations."
            },
            "credentialsEnv": {
                "type": "object",
                "additionalProperties": False,
                "description": "The NAMES of the environment variables holding the credentials, never the values. Unset means the SDK's ambient credentials, which is what a workload identity provides.",
                "properties": {
                    "accessKeyID": {
                        "type": "string",
                        "minLength": 1
                    },
                    "secretAccessKey": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "required": [
                    "accessKeyID",
                    "secretAccessKey"
                ]
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/drain.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/drain.json",
        "title": "drain",
        "description": "How long the service may take to finish in-flight work after SIGTERM. It is one number shared with whatever deploys the service: the grace period granted to the process and the pre-stop delay before it are derived from this, so that a draining process is never killed at the moment it would have finished.",
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "seconds": {
                "type": "integer",
                "minimum": 1,
                "default": 20,
                "description": "Seconds to finish in-flight work. Unset means the service's own default, which is only correct if nothing external is counting."
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/listen.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/listen.json",
        "title": "listen",
        "description": "A TCP listener. `address` is a host:port the service binds; an empty host binds every interface.",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "address"
        ],
        "properties": {
            "address": {
                "type": "string",
                "pattern": "^[^\\s]*:[0-9]{1,5}$",
                "description": "host:port, for example \":8080\" or \"127.0.0.1:8080\"."
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/log.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/log.json",
        "title": "log",
        "description": "Structured logging. One level for the whole service: per-package levels are deliberately not part of the contract.",
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "level": {
                "enum": [
                    "debug",
                    "info",
                    "warn",
                    "error"
                ],
                "default": "info",
                "description": "The lowest level that is written."
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/nats-consumer.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/nats-consumer.json",
        "title": "nats-consumer",
        "description": "What a consumer binds to: a stream, a durable name, and the subject it filters. Durable by name, because a consumer that forgets its position on restart replays or loses whatever arrived while it was gone.",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "stream",
            "durable"
        ],
        "properties": {
            "stream": {
                "type": "string",
                "minLength": 1,
                "description": "The stream to consume from. It exists already: a service does not create the stream it reads."
            },
            "durable": {
                "type": "string",
                "minLength": 1,
                "description": "The durable consumer name. Shared by every replica of this component, which is what makes them one consumer group rather than several."
            },
            "subject": {
                "type": "string",
                "minLength": 1,
                "description": "Filter the stream to this subject. Unset consumes everything the stream holds."
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/nats.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/nats.json",
        "title": "nats",
        "description": "A NATS connection, and nothing else. What a service does with the connection — publish to a subject, bind a durable consumer to a stream — differs per component and is described beside it: a publisher with a `consumer` field it never reads is a field somebody will eventually set.",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "url"
        ],
        "properties": {
            "url": {
                "type": "string",
                "minLength": 1,
                "description": "The server URL, for example nats://nats:4222."
            },
            "tokenFile": {
                "type": "string",
                "minLength": 1,
                "description": "Path to a file holding the token the client authenticates with, mounted by the platform and re-read on every reconnect so that a rotated token is picked up without a restart. It is the workload's own account token: the broker asks an authorisation service who the bearer is, and that service answers from the account rather than from anything the client claims. Unset with `tls` unset means no authentication, which is a test configuration and not a deployment; unset with `tls` set means the certificate is the credential."
            },
            "tls": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "caFile"
                ],
                "description": "Connect over TLS and authenticate with the service's own workload identity instead of a token. The certificate presented is the one the service's own top-level `tls` block loads (its mode must not be `off`); the broker maps the identity in it to a user with its own permissions, so what the service may do is the broker's decision and nothing in this file. The certificate is re-read on every connect, so the platform's rotation is picked up without a restart and a rotation drops no connection already made. Only a service that declares this key in its own schema acts on it.",
                "properties": {
                    "caFile": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Path to the trust bundle the BROKER's certificate is verified against. The broker's, not the workload identity's: a broker has a name and no workload identity, and usually a different chain."
                    },
                    "serverName": {
                        "type": "string",
                        "description": "The name the broker's certificate was issued for, when that is not the host in `url`. Empty verifies the host dialled."
                    }
                }
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/platform.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/platform.json",
        "title": "platform",
        "description": "What the platform provides one component of a service chart: the image, the replicas, the account it runs as, how it is probed, where its identity is mounted, which secrets reach it as environment variables, and how it exports telemetry. The shape of the `platform` block of a chart's values, read by the library chart (decision 0009). Nothing here is the service's own configuration: that is the chart's `config` block, which is the service's schema and nothing else.",
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "image": {
                "type": "object",
                "additionalProperties": False,
                "description": "Where the image is. A digest when there is one; a tag only when there is not. Left out, the library reads the chart's own top-level `images.<component>`, the map a release stamps and refuses to publish with an empty digest.",
                "required": [
                    "repository"
                ],
                "properties": {
                    "registry": {
                        "type": "string"
                    },
                    "repository": {
                        "type": "string",
                        "minLength": 1
                    },
                    "tag": {
                        "type": "string"
                    },
                    "digest": {
                        "type": "string",
                        "pattern": "^(sha256:[0-9a-f]{64})?$"
                    }
                }
            },
            "imagePullPolicy": {
                "enum": [
                    "Always",
                    "IfNotPresent",
                    "Never"
                ],
                "description": "Defaults to IfNotPresent."
            },
            "replicas": {
                "type": "integer",
                "minimum": 0,
                "description": "Defaults to 1. A service that must survive a rollout runs more than one: one instance cannot be replaced without a gap whatever the strategy says."
            },
            "strategy": {
                "type": "object",
                "additionalProperties": False,
                "description": "The rolling update. The defaults make a rollout gapless: the replacement is READY before the incumbent is touched.",
                "properties": {
                    "maxUnavailable": {
                        "type": [
                            "integer",
                            "string"
                        ],
                        "description": "Defaults to 0."
                    },
                    "maxSurge": {
                        "type": [
                            "integer",
                            "string"
                        ],
                        "description": "Defaults to 1."
                    }
                }
            },
            "resources": {
                "type": "object",
                "description": "Kubernetes' own resource requirements. Open: it is passed through unchanged."
            },
            "podSecurity": {
                "type": "object",
                "additionalProperties": False,
                "description": "Who the process is. Every field defaults to 65532, the unprivileged user the runtime images run as; `fsGroup` is the one that matters, because a CSI driver writes what it mounts owned by root.",
                "properties": {
                    "runAsUser": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "runAsGroup": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "fsGroup": {
                        "type": "integer",
                        "minimum": 1
                    }
                }
            },
            "serviceAccount": {
                "type": "object",
                "additionalProperties": False,
                "description": "The account this component runs as. EVERY component has its own, always; `default` is refused. The library grants nothing: annotations are where a platform binds the account to rights outside the cluster, and which mechanism does that is the platform's.",
                "properties": {
                    "create": {
                        "type": "boolean",
                        "description": "False where the platform creates the accounts; they must then exist. Defaults to True."
                    },
                    "name": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Defaults to `<release>-<component>`."
                    },
                    "annotations": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                }
            },
            "service": {
                "type": "object",
                "additionalProperties": False,
                "description": "A component that listens has a Service on the ports of its own `config.listen`; one that does not has none.",
                "properties": {
                    "enabled": {
                        "type": "boolean",
                        "description": "Defaults to whether `config.listen` exists. Enabling one for a component that listens on nothing is refused."
                    }
                }
            },
            "probes": {
                "type": "object",
                "additionalProperties": False,
                "description": "How the component is probed, on the listener its own `config.probes` binds. Liveness is nothing but the process: a probe that checks a dependency restarts a healthy process and makes an outage worse.",
                "properties": {
                    "liveness": {
                        "$ref": "#/$defs/probe"
                    },
                    "readiness": {
                        "$ref": "#/$defs/probe"
                    },
                    "startup": {
                        "$ref": "#/$defs/probe",
                        "description": "Absent means no startup probe. Present, it needs at least one field."
                    }
                }
            },
            "drain": {
                "type": "object",
                "additionalProperties": False,
                "description": "The service's own shutdown budget is `config.drain.seconds`; the library derives the grace period from it and this delay, so the three numbers cannot disagree.",
                "properties": {
                    "preStopSeconds": {
                        "type": "integer",
                        "minimum": 0,
                        "description": "Fail readiness, then wait this long before the drain starts, so that whatever routes traffic has removed this endpoint first. Defaults to 5."
                    }
                }
            },
            "tls": {
                "type": "object",
                "additionalProperties": False,
                "description": "Where the platform mounts the workload identity. The files the component's own `config.tls` names must be under `mountPath`; the render refuses a file that is not.",
                "properties": {
                    "csiDriver": {
                        "type": "string",
                        "minLength": 1,
                        "description": "The driver that mounts the identity. The platform's, so there is no default; required once the identity is mounted."
                    },
                    "mountPath": {
                        "type": "string",
                        "pattern": "^/.+",
                        "description": "Defaults to /var/run/identity."
                    },
                    "mount": {
                        "type": "boolean",
                        "description": "Defaults to whether `config.tls.mode` is permissive or strict. True mounts the identity into a component that presents none of its own, because the release does; False never mounts it."
                    }
                }
            },
            "telemetry": {
                "type": "object",
                "additionalProperties": False,
                "description": "OpenTelemetry's own environment variables (decision 0006): they leave the chart as variables, never as configuration keys. No endpoint means do not export.",
                "properties": {
                    "serviceName": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Defaults to `<release>-<component>`."
                    },
                    "endpoint": {
                        "type": "string"
                    },
                    "protocol": {
                        "enum": [
                            "grpc",
                            "http/protobuf",
                            "http/json"
                        ]
                    },
                    "tracesSampler": {
                        "type": "string"
                    },
                    "sampleRatio": {
                        "type": [
                            "string",
                            "number"
                        ]
                    },
                    "resourceAttributes": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                }
            },
            "secrets": {
                "type": "object",
                "description": "The environment variables that carry SECRETS, and nothing else (decision 0002): variable name to the Secret and key its value comes from. The configuration file names the VARIABLE; the value never appears in a values file or a render.",
                "propertyNames": {
                    "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
                },
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": [
                        "secretName",
                        "key"
                    ],
                    "properties": {
                        "secretName": {
                            "type": "string",
                            "minLength": 1
                        },
                        "key": {
                            "type": "string",
                            "minLength": 1
                        }
                    }
                }
            },
            "env": {
                "type": "array",
                "description": "Environment a platform CLIENT LIBRARY reads (a database client's connection variables, for example), never the service's own configuration: a service takes no other structural input than its file (decision 0002). A secret does not belong here; declare it in `secrets`.",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": [
                        "name",
                        "value"
                    ],
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                }
            },
            "volumes": {
                "type": "array",
                "description": "Extra pod volumes, in Kubernetes' own shape, for what a client library mounts (a trust bundle, a password file). Open: passed through unchanged.",
                "items": {
                    "type": "object",
                    "required": [
                        "name"
                    ]
                }
            },
            "volumeMounts": {
                "type": "array",
                "description": "The mounts for `volumes`, in Kubernetes' own shape.",
                "items": {
                    "type": "object",
                    "required": [
                        "name",
                        "mountPath"
                    ]
                }
            },
            "config": {
                "type": "object",
                "additionalProperties": False,
                "description": "How the file reaches the process. The path is ONE argument or ONE environment variable, never both (decision 0002).",
                "properties": {
                    "fileName": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Defaults to `<component>.yaml`."
                    },
                    "mountPath": {
                        "type": "string",
                        "pattern": "^/.+",
                        "description": "The directory the ConfigMap is mounted at. Defaults to `/etc/<chart name>`."
                    },
                    "pathFlag": {
                        "type": "string",
                        "minLength": 1,
                        "description": "The argument that carries the path. Defaults to `-config`."
                    },
                    "pathEnv": {
                        "type": "string",
                        "minLength": 1,
                        "description": "When set, the path is passed in this environment variable instead of an argument."
                    }
                }
            },
            "configMap": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "annotations": {
                        "type": "object",
                        "description": "For a ConfigMap that must be a hook resource: a pre-install job cannot mount one the release has not created yet.",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "$defs": {
            "probe": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "path": {
                        "type": "string",
                        "pattern": "^/"
                    },
                    "periodSeconds": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "initialDelaySeconds": {
                        "type": "integer",
                        "minimum": 0
                    },
                    "timeoutSeconds": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "successThreshold": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "failureThreshold": {
                        "type": "integer",
                        "minimum": 1
                    }
                }
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/postgres.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/postgres.json",
        "title": "postgres",
        "description": "A PostgreSQL connection. The URL carries no password: it names the environment variable that does.",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "url"
        ],
        "properties": {
            "url": {
                "type": "string",
                "pattern": "^postgres(ql)?://",
                "allOf": [
                    {
                        "description": "No password in the user information: postgres://user:password@host is refused, postgres://user@host is not.",
                        "not": {
                            "pattern": "^postgres(ql)?://[^/?#@]*:[^/?#@]*@"
                        }
                    },
                    {
                        "description": "No password as a query parameter: password= and sslpassword= are refused. passfile= is allowed, because it names a file rather than carrying a secret.",
                        "not": {
                            "pattern": "[?&](password|sslpassword)="
                        }
                    },
                    {
                        "description": "No percent-encoded parameter name: a driver decodes the name before it reads it, so %70assword= is password= by another spelling.",
                        "not": {
                            "pattern": "[?&][^=&#]*%[^=&#]*="
                        }
                    }
                ],
                "description": "A connection URL without credentials, for example postgres://user@host:5432/dbname?sslmode=require. A password in the user information or in a password or sslpassword parameter is refused: the file is rendered into objects people read, and the password belongs to passwordEnv."
            },
            "passwordEnv": {
                "type": "string",
                "minLength": 1,
                "description": "The NAME of the environment variable holding the password. Unset means the connection needs none."
            },
            "maxConnections": {
                "type": "integer",
                "minimum": 1,
                "default": 10,
                "description": "Pool size for this instance. Sized against the server's limit divided by the number of instances, not guessed."
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/probes.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/probes.json",
        "title": "probes",
        "description": "The health listener. Separate from the service's own traffic, so that readiness is answerable when the service's listener is saturated, and so that a probe is not reachable from outside.",
        "type": "object",
        "additionalProperties": False,
        "required": [
            "address"
        ],
        "properties": {
            "address": {
                "type": "string",
                "pattern": "^[^\\s]*:[0-9]{1,5}$",
                "description": "host:port for /health/live and /health/ready."
            }
        }
    },
    "https://github.com/truvity/policy/schemas/fragments/tls.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/fragments/tls.json",
        "title": "tls",
        "description": "Mutually authenticated transport, where the platform provides the identity. A workload presents a certificate it did not mint, reloads it without restarting, and admits peers by the account they run as rather than by the address they call from. Absent, or mode 'off', means cleartext: a service must be installable on a platform that provides none of this.",
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "mode": {
                "enum": [
                    "off",
                    "permissive",
                    "strict"
                ],
                "default": "off",
                "description": "'off' serves cleartext only. 'permissive' serves BOTH, on two ports, so that an edge can migrate one side at a time without a coordinated window. 'strict' serves only the authenticated port. One listener cannot be both in every runtime, which is why permissive is two ports rather than one that sniffs."
            },
            "address": {
                "type": "string",
                "minLength": 1,
                "description": "Where the authenticated listener binds under 'permissive', beside the cleartext one. Under 'strict' there is one listener and it is the service's own, so this is unused: the protocol changes, the address does not, and nothing downstream has to be told."
            },
            "certFile": {
                "type": "string",
                "minLength": 1,
                "description": "The certificate this workload presents, mounted and rotated by the platform. Re-read when it changes, never cached for the process's lifetime: a one-hour certificate outlives no deployment."
            },
            "keyFile": {
                "type": "string",
                "minLength": 1,
                "description": "Its private key. It lives in the pod and never in a secret, so a workload that can read secrets in its namespace still cannot read a neighbour's key."
            },
            "caFile": {
                "type": "string",
                "minLength": 1,
                "description": "The authority peers are verified against, distributed by the platform as a trust bundle."
            },
            "trustDomain": {
                "type": "string",
                "minLength": 1,
                "description": "The root of every identity this service will admit, for example 'example.internal'. A peer whose identity belongs to another trust domain is refused before its account is even considered."
            },
            "peers": {
                "type": "array",
                "description": "Who may call. Each entry is an ACCOUNT, not an address: an address resolves to whoever holds it today. An empty list admits no one, which is the correct default for a service nobody has been granted.",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": [
                        "namespace",
                        "serviceAccount"
                    ],
                    "properties": {
                        "namespace": {
                            "type": "string",
                            "minLength": 1
                        },
                        "serviceAccount": {
                            "type": "string",
                            "minLength": 1
                        }
                    }
                }
            }
        },
        "allOf": [
            {
                "if": {
                    "properties": {
                        "mode": {
                            "enum": [
                                "permissive",
                                "strict"
                            ]
                        }
                    },
                    "required": [
                        "mode"
                    ]
                },
                "then": {
                    "required": [
                        "certFile",
                        "keyFile",
                        "caFile",
                        "trustDomain"
                    ]
                }
            }
        ]
    },
    "https://github.com/truvity/policy/schemas/service.json": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/truvity/policy/schemas/service.json",
        "title": "service",
        "description": "The envelope every service's configuration carries. A service references this from its own schema with allOf, and adds its own properties beside it. What is in here is what EVERY component has, including a job that exits and a consumer that answers nothing: somewhere to report health, a log level, a shutdown budget, and which version of its document it is. A listener is not one of those — see docs/contracts/config.md.",
        "type": "object",
        "properties": {
            "apiVersion": {
                "type": "string",
                "pattern": "^[a-z0-9]([a-z0-9.-]*[a-z0-9])?/[a-z0-9]([a-z0-9-]*[a-z0-9])?/v[1-9][0-9]*$",
                "description": "Which version of which kind of document this is: <group>/<kind>/v<N>. Absent means v1. The loader reads the version before it validates anything, picks that version's schema, and refuses a version this binary does not read (a binary reads N and N-1) — see docs/contracts/config.md. A service may narrow it to its own kind with a const."
            },
            "probes": {
                "$ref": "https://github.com/truvity/policy/schemas/fragments/probes.json"
            },
            "log": {
                "$ref": "https://github.com/truvity/policy/schemas/fragments/log.json"
            },
            "drain": {
                "$ref": "https://github.com/truvity/policy/schemas/fragments/drain.json"
            }
        },
        "required": [
            "probes"
        ]
    }
}
