// Code generated by `just ts-schemas`. DO NOT EDIT.
//
// The shapes this repository publishes, by the identifier each carries. They
// are values here rather than files so that the published package is
// self-contained and validation never reaches the network.

export const SCHEMA_BASE = "https://github.com/truvity/policy/schemas/";

export const sharedSchemas: Record<string, object> = {
  "https://github.com/truvity/policy/schemas/fragments/bucket.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/bucket.json",
    "title": "bucket",
    "description": "An object store addressed by the S3 API. The vendor is not part of the configuration: an endpoint, a region and a path-style flag are enough to reach a cloud service, an in-cluster store or a test double, and a service that hard-codes one of them cannot be tested without it.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "name"
    ],
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1,
        "description": "The bucket. It exists already: a service does not create its own store."
      },
      "region": {
        "type": "string",
        "minLength": 1,
        "description": "The region the bucket is in."
      },
      "endpoint": {
        "type": "string",
        "format": "uri",
        "description": "Override the API endpoint. Unset means the SDK's own resolution for the region."
      },
      "ca": {
        "type": "string",
        "minLength": 1,
        "description": "Path to a certificate authority bundle the platform mounts, for a store whose endpoint is not signed by a public root. A store inside somebody's own network is the ordinary case, not the exotic one. Unset means the system trust store."
      },
      "pathStyle": {
        "type": "boolean",
        "default": false,
        "description": "Address the bucket as a path rather than as a host. Required by most non-cloud implementations."
      },
      "credentialsEnv": {
        "type": "object",
        "additionalProperties": false,
        "description": "The NAMES of the environment variables holding the credentials, never the values. Unset means the SDK's ambient credentials, which is what a workload identity provides.",
        "properties": {
          "accessKeyID": {
            "type": "string",
            "minLength": 1
          },
          "secretAccessKey": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "accessKeyID",
          "secretAccessKey"
        ]
      }
    }
  },
  "https://github.com/truvity/policy/schemas/fragments/drain.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/drain.json",
    "title": "drain",
    "description": "How long the service may take to finish in-flight work after SIGTERM. It is one number shared with whatever deploys the service: the grace period granted to the process and the pre-stop delay before it are derived from this, so that a draining process is never killed at the moment it would have finished.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "seconds": {
        "type": "integer",
        "minimum": 1,
        "default": 20,
        "description": "Seconds to finish in-flight work. Unset means the service's own default, which is only correct if nothing external is counting."
      }
    }
  },
  "https://github.com/truvity/policy/schemas/fragments/listen.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/listen.json",
    "title": "listen",
    "description": "A TCP listener. `address` is a host:port the service binds; an empty host binds every interface.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "address"
    ],
    "properties": {
      "address": {
        "type": "string",
        "pattern": "^[^\\s]*:[0-9]{1,5}$",
        "description": "host:port, for example \":8080\" or \"127.0.0.1:8080\"."
      }
    }
  },
  "https://github.com/truvity/policy/schemas/fragments/log.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/log.json",
    "title": "log",
    "description": "Structured logging. One level for the whole service: per-package levels are deliberately not part of the contract.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "level": {
        "enum": [
          "debug",
          "info",
          "warn",
          "error"
        ],
        "default": "info",
        "description": "The lowest level that is written."
      }
    }
  },
  "https://github.com/truvity/policy/schemas/fragments/nats-consumer.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/nats-consumer.json",
    "title": "nats-consumer",
    "description": "What a consumer binds to: a stream, a durable name, and the subject it filters. Durable by name, because a consumer that forgets its position on restart replays or loses whatever arrived while it was gone.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "stream",
      "durable"
    ],
    "properties": {
      "stream": {
        "type": "string",
        "minLength": 1,
        "description": "The stream to consume from. It exists already: a service does not create the stream it reads."
      },
      "durable": {
        "type": "string",
        "minLength": 1,
        "description": "The durable consumer name. Shared by every replica of this component, which is what makes them one consumer group rather than several."
      },
      "subject": {
        "type": "string",
        "minLength": 1,
        "description": "Filter the stream to this subject. Unset consumes everything the stream holds."
      }
    }
  },
  "https://github.com/truvity/policy/schemas/fragments/nats.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/nats.json",
    "title": "nats",
    "description": "A NATS connection, and nothing else. What a service does with the connection — publish to a subject, bind a durable consumer to a stream — differs per component and is described beside it: a publisher with a `consumer` field it never reads is a field somebody will eventually set.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "url"
    ],
    "properties": {
      "url": {
        "type": "string",
        "minLength": 1,
        "description": "The server URL, for example nats://nats:4222."
      },
      "tokenFile": {
        "type": "string",
        "minLength": 1,
        "description": "Path to a file holding the token the client authenticates with, mounted by the platform and re-read on every reconnect so that a rotated token is picked up without a restart. It is the workload's own account token: the broker asks an authorisation service who the bearer is, and that service answers from the account rather than from anything the client claims. Unset means no authentication, which is a test configuration and not a deployment."
      }
    }
  },
  "https://github.com/truvity/policy/schemas/fragments/postgres.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/postgres.json",
    "title": "postgres",
    "description": "A PostgreSQL connection. The URL carries no password: it names the environment variable that does.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "url"
    ],
    "properties": {
      "url": {
        "type": "string",
        "pattern": "^postgres(ql)?://",
        "description": "A connection URL without credentials, for example postgres://user@host:5432/dbname?sslmode=require."
      },
      "passwordEnv": {
        "type": "string",
        "minLength": 1,
        "description": "The NAME of the environment variable holding the password. Unset means the connection needs none."
      },
      "maxConnections": {
        "type": "integer",
        "minimum": 1,
        "default": 10,
        "description": "Pool size for this instance. Sized against the server's limit divided by the number of instances, not guessed."
      }
    }
  },
  "https://github.com/truvity/policy/schemas/fragments/probes.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/fragments/probes.json",
    "title": "probes",
    "description": "The health listener. Separate from the service's own traffic, so that readiness is answerable when the service's listener is saturated, and so that a probe is not reachable from outside.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "address"
    ],
    "properties": {
      "address": {
        "type": "string",
        "pattern": "^[^\\s]*:[0-9]{1,5}$",
        "description": "host:port for /health/live and /health/ready."
      }
    }
  },
  "https://github.com/truvity/policy/schemas/service.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/truvity/policy/schemas/service.json",
    "title": "service",
    "description": "The envelope every service's configuration carries. A service references this from its own schema with allOf, and adds its own properties beside it.",
    "type": "object",
    "properties": {
      "listen": {
        "$ref": "https://github.com/truvity/policy/schemas/fragments/listen.json"
      },
      "probes": {
        "$ref": "https://github.com/truvity/policy/schemas/fragments/probes.json"
      },
      "log": {
        "$ref": "https://github.com/truvity/policy/schemas/fragments/log.json"
      },
      "drain": {
        "$ref": "https://github.com/truvity/policy/schemas/fragments/drain.json"
      }
    },
    "required": [
      "probes"
    ]
  }
};
